"""
Bright Data Scraper Studio & Scraping Browser Integration Adapter.

Provides seamless integration with:
1. Bright Data Scraper Studio (triggering custom scrapers, polling jobs, and ingesting structured records).
2. Bright Data Scraping Browser (Playwright CDP connection with automated fingerprint rotation and CAPTCHA solving).
3. Piping Scraper Studio records through the 9-layer Self-Healing pipeline for validation, anomaly detection, and AI repair.
"""

from __future__ import annotations

import os
import asyncio
from typing import Any, Optional, Dict, List
import httpx
import structlog
from playwright.async_api import Browser, Playwright

logger = structlog.get_logger(__name__)


class BrightDataScraperStudioClient:
    """
    Client for interacting with custom scrapers built in Bright Data Scraper Studio
    and connecting Playwright to Bright Data's Scraping Browser.
    """

    BASE_URL = "https://api.brightdata.com"

    def __init__(
        self,
        api_key: Optional[str] = None,
        scraper_id: Optional[str] = None,
        scraping_browser_ws: Optional[str] = None,
    ) -> None:
        self.api_key = api_key or os.environ.get("BRIGHT_DATA_API_KEY")
        self.scraper_id = scraper_id or os.environ.get("BRIGHT_DATA_SCRAPER_ID")
        self.scraping_browser_ws = scraping_browser_ws or os.environ.get("BRIGHT_DATA_SCRAPING_BROWSER_WS")

    def _get_headers(self) -> Dict[str, str]:
        if not self.api_key:
            raise ValueError("BRIGHT_DATA_API_KEY is required to authenticate with Bright Data Scraper Studio.")
        return {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

    async def trigger_custom_scraper(
        self,
        inputs: List[Dict[str, Any]],
        scraper_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Trigger an asynchronous collection job for a custom scraper built in Scraper Studio.
        
        Args:
            inputs: List of target URL objects (e.g. [{"url": "https://books.toscrape.com/..."}])
            scraper_id: Custom scraper identifier created in Scraper Studio.
            
        Returns:
            Dictionary containing the triggered snapshot_id / collection_id.
        """
        target_scraper = scraper_id or self.scraper_id
        if not target_scraper:
            raise ValueError("No scraper_id specified or found in BRIGHT_DATA_SCRAPER_ID.")

        endpoint = f"{self.BASE_URL}/dca/trigger"
        params = {
            "collector": target_scraper,
            "queue_next": 1,
        }

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                endpoint,
                headers=self._get_headers(),
                params=params,
                json=inputs,
            )
            response.raise_for_status()
            data = response.json()
            logger.info("bright_data_scraper_triggered", scraper_id=target_scraper, response=data)
            return data

    async def get_job_status(self, snapshot_id: str) -> Dict[str, Any]:
        """
        Poll status of an active Scraper Studio batch job.
        """
        endpoint = f"{self.BASE_URL}/dca/get_status"
        params = {"snapshot_id": snapshot_id}

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.get(
                endpoint,
                headers=self._get_headers(),
                params=params,
            )
            response.raise_for_status()
            return response.json()

    async def fetch_results(self, snapshot_id: str, format_type: str = "json") -> List[Dict[str, Any]]:
        """
        Retrieve structured records generated by a Scraper Studio collection.
        """
        endpoint = f"{self.BASE_URL}/dca/get_result"
        params = {
            "snapshot_id": snapshot_id,
            "format": format_type,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.get(
                endpoint,
                headers=self._get_headers(),
                params=params,
            )
            response.raise_for_status()
            data = response.json()
            logger.info("bright_data_results_fetched", snapshot_id=snapshot_id, record_count=len(data) if isinstance(data, list) else 1)
            return data if isinstance(data, list) else [data]

    async def collect_sync(
        self,
        inputs: List[Dict[str, Any]],
        scraper_id: Optional[str] = None,
        poll_interval: float = 3.0,
        max_timeout: float = 180.0,
    ) -> List[Dict[str, Any]]:
        """
        Trigger a custom Scraper Studio scraper and wait synchronously for the structured results.
        """
        trigger_res = await self.trigger_custom_scraper(inputs, scraper_id=scraper_id)
        snapshot_id = trigger_res.get("collection_id") or trigger_res.get("snapshot_id")
        
        if not snapshot_id:
            raise RuntimeError(f"Bright Data Scraper Studio trigger returned no snapshot_id: {trigger_res}")

        start_time = asyncio.get_event_loop().time()
        while True:
            elapsed = asyncio.get_event_loop().time() - start_time
            if elapsed > max_timeout:
                raise TimeoutError(f"Scraper Studio collection {snapshot_id} timed out after {max_timeout}s")

            status_res = await self.get_job_status(snapshot_id)
            status = status_res.get("status")
            logger.info("bright_data_polling_status", snapshot_id=snapshot_id, status=status, elapsed=round(elapsed, 1))

            if status == "ready":
                return await self.fetch_results(snapshot_id)
            elif status in ("failed", "error"):
                raise RuntimeError(f"Scraper Studio collection {snapshot_id} failed: {status_res}")

            await asyncio.sleep(poll_interval)

    async def connect_scraping_browser(self, playwright: Playwright) -> Browser:
        """
        Connects Playwright over CDP to Bright Data's Scraping Browser.
        
        Enables seamless bypassing of anti-bot protections, Cloudflare/Datadome WAFs,
        and automated CAPTCHA resolution.
        """
        if not self.scraping_browser_ws:
            raise ValueError(
                "BRIGHT_DATA_SCRAPING_BROWSER_WS is required to connect to Bright Data Scraping Browser. "
                "Format: wss://<user>:<pass>@brd.superproxy.io:9222"
            )

        logger.info("connecting_to_bright_data_scraping_browser")
        browser = await playwright.chromium.connect_over_cdp(self.scraping_browser_ws)
        logger.info("connected_to_bright_data_scraping_browser")
        return browser
